### ISSUE TITLE
Privacy policy link on Disassembler's Google Play listing is out-of-date

### ISSUE THREAD

**Issue by JavkhlanK** [elmurzaev/elmurzaev.github.io#3]
The Google Play listing for Disassembler (https://play.google.com/store/apps/details?id=com.mcal.disassembler) is redirecting to https://github.com/elmurzaev/elmurzaev.github.io/blob/master/mobilearn/privacy.html, even though it should be https://elmurzaev.github.io/privacy.html or https://github.com/elmurzaev/elmurzaev.github.io/blob/master/privacy.html.

**Comment by elmurzaev** [comment]
@JavkhlanK it's not my app. Contact that developer directly.

**Comment by JavkhlanK** [comment]
Oh, that's weird. I wonder why they'd link your privacy policy in their own app's listing then.
